# Generated by Django 5.2.7 on 2025-10-20 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
    ]
