# Generated by Django 5.2.7 on 2025-10-20 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizzes', '0002_attempt_is_flagged'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='choice',
            options={'ordering': ['question', 'id']},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['quiz', 'id']},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['title']},
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='display_order',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='question',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='choice',
            name='text',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Quizzes.category'),
        ),
        migrations.AlterField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
