# Generated by Django 5.2.7 on 2025-10-18 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quizzes', '0002_quiz_category_quiz_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['-title'], 'verbose_name_plural': 'Quizzes'},
        ),
    ]
