# Generated by Django 5.2.7 on 2025-10-18 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizzes', '0003_alter_quiz_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['display_order', '-title'], 'verbose_name_plural': 'Quizzes'},
        ),
        migrations.AddField(
            model_name='quiz',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
