# Generated by Django 5.2.7 on 2025-10-18 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizzes', '0004_alter_quiz_options_quiz_display_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.'),
        ),
    ]
