# Generated by Django 5.2.7 on 2025-10-21 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quizzes', '0007_alter_attempt_options_alter_category_options_and_more'),
        ('Quizzes', '0008_fix_categories_order'),
    ]

    operations = [
    ]
